### PR TITLE
Add stacked bar chart value labels (#60) and a horizontal stacked bar chart (#39)

### PR DESCRIPTION
**Pull request by pdt256**

### CODE REVIEW

**Comment by pdt256** [comment]
This PR enables value labels:
Stacked Bar with Labels

**Comment by pdt256** [comment]
This PR also adds a horizontal stacked bar chart. I'm not thrilled about using `StackedBarChart.IsHorizontal` to switch to a horizontal style chart as suggested by [#39](https://github.com/wcharczuk/go-chart/issues/39#issuecomment-307648259)
The code would be cleaner with fewer duplicate methods if there was a separate `HorizontalStackedBarChart`.

Let me know your thoughts and I can modify this PR.

Horizontal Stacked Bar Chart

**Comment by detunized** [comment]
Is there a technical reason this is not merged? Looks like an awesome feature.

**Comment by pdt256** [comment]
1 review is required. Can someone with write access please review this PR?

**Comment by pdt256** [comment]
ping

**Comment by pdt256** [comment]
I have updated this PR to conform to the upstream changes. Is there anything else that needs to be addressed?

**Comment by skillful-alex** [comment]
I need such a chart. So I will import github.com/pdt256/go-chart

**Comment by pdt256** [comment]
> I need such a chart. So I will import github.com/pdt256/go-chart

I had to add a `go.mod` file in the project root directory to allow local imports to continue to work:
```
module github.com/wcharczuk/go-chart

go 1.13

require (
	github.com/blend/go-sdk v2.0.0+incompatible
	github.com/golang/freetype v0.0.0-20170609003504-e2365dfdc4a0
	golang.org/x/image v0.0.0-20191009234506-e7c1f5e7dbb8
	golang.org/x/tools v0.0.0-20191115202509-3a792d9c32b2 // indirect
)
```

Then modify the `go.mod` file in another project to import go-chart properly:
```
replace github.com/wcharczuk/go-chart => ../../../github.com/pdt256/go-chart
```

**Comment by wcharczuk** [comment]
hey everyone, sorry been knee deep in work stuff for the past few months so have been MIA on this repo. pr looks good, going to merge.

**Comment by wcharczuk** [comment]
One caveat with the above is that go.mod currently isn't supported by `blend/go-sdk` so making this repo support go.mod is a bit of a lift, but can attack that in the next month or so

**Comment by LazarenkoA** [comment]
@pdt256 
there is an example of how to achieve the same diagram as yours, I tried to add `IsHorizontal` to this example https://github.com/wcharczuk/go-chart/blob/master/examples/stacked_bar/main.go, but something didn't work?

**Pull request merged**
