### PR TITLE
Adds the ability to draw an XY scatter plot.

### PR DESCRIPTION
**Pull request by wcharczuk**
This PR introduces two new fields on `Style`: `DotWidth` and `DotColor`. It also tweaks some aspects of the raster renderer, namely the `.Circle` function and some of the inner workings of the drawing package.

Important consideration; so far only `Draw.LineSeries` uses these new fields, support in other types of plots is ongoing.

Also adds an example for scatter plots in `_examples/scatter/main.go`.

### CODE REVIEW

**Comment by mattdoran** [comment]
Looking good when I specify the full style like you did in your sample.

However the default rendering without style seems to have regressed. I get a black and white filled graph ... not auto color assignment.

See graphs ....  from master with default style

gc-durations-master

and scatter with default style:

gc-durations-scatter

Another thing (which could be my misunderstanding) ..  I also wanted to get auto-color for the scatter so deleted the explicit Red color from the sample and the nothing was rendered.   Is this related to the above, or do I need to ask explicitly for auto-coloring?

**Comment by wcharczuk** [comment]
good catch on the regressions, i really need to add tests to validate the draw functions.

i do auto coloring for the series stroke colors, can for sure do that for the dot colors using the same method.

**Comment by wcharczuk** [comment]
@mattdoran can you do a pull and try rendering that chart again; i've tweaked LineSeries and added auto coloring, going to add some regression tests now to make sure that doesn't happen again

**Comment by mattdoran** [comment]
Looking good @wcharczuk

Default style draws lines auto colored properly.   

The scatter also auto colors too now.

👍 

PS: I have other issues/suggestions to raise ... is there a better place to do this than just in an issue?   Hint what's on my mind: Smarter tick marker positioning (I've been looking at matplotlib's algorithm) ... and performance plotting lots of points is slow and I've started some profiling.

**Comment by wcharczuk** [comment]
cool! 

if you have other suggestions, log them as issues so i'm aware of them, but feel free to hack away.

re: performance, yeah there is a huge discrepancy between SVG and PNG rendering. my hunch is it's because the `drawing` library internally calls into font apis to do actual painting. any help here would be greatly appreciated!

going to merge this branch once i get a regression test in place for the drawing colors

**Pull request merged**
